In [4]:
import tensorflow as tf
import numpy as np

In [5]:
# Creating tensors
t1 = tf.constant([[1, 2], [3, 4]])
t2 = tf.constant([[5, 6], [7, 8]])
print("Tensor 1:", t1.numpy())
print("Tensor 2:", t2.numpy())

Tensor 1: [[1 2]
 [3 4]]
Tensor 2: [[5 6]
 [7 8]]


In [6]:
# Basic tensor operations
add_result = tf.add(t1, t2)
mul_result = tf.multiply(t1, t2)
dot_result = tf.tensordot(t1, t2, axes=1)
print("Addition Result:", add_result.numpy())
print("Multiplication Result:", mul_result.numpy())
print("Dot Product Result:", dot_result.numpy())

Addition Result: [[ 6  8]
 [10 12]]
Multiplication Result: [[ 5 12]
 [21 32]]
Dot Product Result: [[19 22]
 [43 50]]


In [7]:
# Einsum operations
a = tf.constant(np.random.rand(2, 3))
b = tf.constant(np.random.rand(3, 4))

einsum_result = tf.einsum('ij,jk->ik', a, b)
print("Einsum Result:", einsum_result.numpy())

Einsum Result: [[0.38586811 0.37999059 0.47149447 0.82857458]
 [0.55468711 0.48943073 0.55562975 1.21307679]]


In [8]:
# More complex einsum expressions
x = tf.constant(np.random.rand(2, 3, 4))
y = tf.constant(np.random.rand(4, 5))

einsum_complex = tf.einsum('ijk,kl->ijl', x, y)
print("Complex Einsum Result:", einsum_complex.numpy())

Complex Einsum Result: [[[1.12234017 0.72312709 0.6011094  0.96202034 0.88969741]
  [0.52117148 0.30445766 0.27942107 0.34721608 0.36844091]
  [1.18526989 0.58127368 0.58224262 0.56208281 0.71352215]]

 [[1.14261034 0.65566782 0.48108129 0.90222834 0.80561127]
  [1.84746914 1.0378629  1.03511695 1.14706053 1.30046479]
  [1.66455126 1.11515204 0.79430098 1.27689519 1.16523347]]]


In [9]:
# Reshaping tensors
reshaped = tf.reshape(t1, [4, 1])
print("Reshaped Tensor:", reshaped.numpy())

Reshaped Tensor: [[1]
 [2]
 [3]
 [4]]


In [10]:
# Transposing tensors
transposed = tf.transpose(t1)
print("Transposed Tensor:", transposed.numpy())

Transposed Tensor: [[1 3]
 [2 4]]


In [11]:
# Expanding and squeezing dimensions
expanded = tf.expand_dims(t1, axis=0)
squeezed = tf.squeeze(expanded)
print("Expanded Tensor:", expanded.numpy())
print("Squeezed Tensor:", squeezed.numpy())

Expanded Tensor: [[[1 2]
  [3 4]]]
Squeezed Tensor: [[1 2]
 [3 4]]


In [12]:
# Stacking tensors
stacked = tf.stack([t1, t2], axis=0)
print("Stacked Tensor:", stacked.numpy())

Stacked Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
# Broadcasting example
a = tf.constant([1, 2, 3])
b = tf.constant([[1], [2], [3]])
broadcasted_addition = a + b
print("Broadcasted Addition:", broadcasted_addition.numpy())

Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [15]:
# Tensor slicing
sliced = t1[:, 1]
print("Sliced Tensor:", sliced.numpy())

Sliced Tensor: [2 4]
